### ISSUE TITLE
Suggestion: Option to set increments in speed

### ISSUE THREAD

**Issue by doctopus** [filipesabella/speed-reader#4]
Currently the default increments of speed is 50. It would be nice to have a smaller increment, or better even an option to set the increment in the setting. Thank you.

**Comment by filipesabella** [comment]
Great suggestion, thank you.

It has been implemented and released on 1.3. Please let me know if it's working well.

**Comment by doctopus** [comment]
Thank you so much for implementing the request. It works perfectly.
